#1- Nome amigavel da tabela
#2- Descricao da tabela
#3- Schema de campos da tabela
#4- Descricao dos campos da tabela
#5- Typo de gravacao no bigquery
    # WRITE_EMPTY - somente inclui se não tiver dados na tabela
    # WRITE_APPEND - adiciona dados se a tabela já existir
    # WRITE_TRUNCATE - apaga a tabela antes de inserir os valores
#6- Tags da Dag
#7- Scheduler da Dag @daily, @hourly, @weekly, @monthly, @yearly, * 0/6 * * * * 
#8- Particionamento do bigquery 
    #type: (HOUR, DAY, MONTH, YEAR), 
    #field: (campo da tabela) 
    #require_partition_filter: (True, False)
#9- cluster_fields do bigquery, recebe lista de campos [campoA, campoB] 

class BigquerySchema:
    def __init__(self):
        self.city = {
            1: "Cidades",
            2: "Tabela de cadastro de cidades, populadas pelo usuário",
            3: [
                {'name': 'id', 'type': 'INTEGER', 'mode': 'NULLABLE'}, 
                {'name': 'name', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'state_id', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'created', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'},
                {'name': 'enabled', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'bigquery_ingestion', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'}
            ],
            4: [
                {'name':'id', 'description':'ID da cidade'}, 
                {'name':'name', 'description':'Nome da cidade'}, 
                {'name':'state_id', 'description':'ID do estado'}, 
                {'name':'created', 'description':'Data de criação'}, 
                {'name':'enabled', 'description':'Cidade habilitada?'}, 
                {'name':'bigquery_ingestion', 'description':'Data da última carga'}, 
            ],
            5: 'WRITE_TRUNCATE',
            6: ['postgres', 'truncate', 'city'],
            7: '0 0/6 * * *',
            8: None,
            9: None
        }
        self.user_account = {
            1: "Contas de usuários",
            2: "Tabela de contas de usuários B2C, B2B e PRO",
            3:[
                {'name': 'id', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'email', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'name', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'phone', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'address', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'state_id', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'city_id', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'is_admin', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'created', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'},
                {'name': 'device_id', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'last_name', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'token_fb', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'token_gp', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'cep', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'profile_picture', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'origin_id', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'flg_ativo', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'last_login_at', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'},
                {'name': 'flg_email_validated', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'flg_phone_validated', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'deleted_at', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'},
                {'name': 'flg_password_defined', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'facebook_id', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'gender', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'business_register', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'changed_picture', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'origin_comment', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'unsubscribe_token', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'birthday', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'asked_info_at', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'},
                {'name': 'source', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'fc_restore_id', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'mgm_code', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'mgm_valid_thru', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'},
                {'name': 'cpf', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'phone_validated_at', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'},
                {'name': 'bo_default_url', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'cnpj', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'possible_email', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'partners_email_validated', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'identity_token_apple', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'apple_authorization_code', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'apple_user', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'flg_not_receive_whatsapp', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'updated_at', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'},
                {'name': 'is_critical_customer', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'bigquery_ingestion', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'}
            ],
            4:[
                {"name": "id", "description": "ID do usuário"},
                {"name": "email", "description": "E-mail"},
                {"name": "name", "description": "Nome do usuário"},
                {"name": "phone", "description": "Telefone"},
                {"name": "address", "description": "Endereço"},
                {"name": "state_id", "description": "ID do estado"},
                {"name": "city_id", "description": "ID da cidade"},
                {"name": "is_admin", "description": "É administrador?"},
                {"name": "created", "description": "Data de criação"},
                {"name": "device_id", "description": "ID do dispositivo"},
                {"name": "last_name", "description": "Último nome do usuário"},
                {"name": "token_fb", "description": "Token do Facebook"},
                {"name": "token_gp", "description": "token do google"},
                {"name": "cep", "description": "CEP"},
                {"name": "profile_picture", "description": "Foto do perfil"},
                {"name": "origin_id", "description": "ID de origem (mobile, web)"},
                {"name": "flg_ativo", "description": "Está ativo?"},
                {"name": "last_login_at", "description": "Data do ultimo login"},
                {"name": "flg_email_validated", "description": "Email está validado?"},
                {"name": "flg_phone_validated", "description": "Telefone está validado?"},
                {"name": "deleted_at", "description": "Data de inativação"},
                {"name": "flg_password_defined", "description": "Senha foi definida?"},
                {"name": "facebook_id", "description": "ID do facebook"},
                {"name": "gender", "description": "Genero"},
                {"name": "business_register", "description": "Registro do negócio"},
                {"name": "changed_picture", "description": "Imagem foi alterada?"},
                {"name": "origin_comment", "description": "Origem do comentario"},
                {"name": "unsubscribe_token", "description": "Token de desinscrição"},
                {"name": "birthday", "description": "Data do aniversário"},
                {"name": "asked_info_at", "description": "Data de pedido de informação"},
                {"name": "source", "description": "Orgigem (mobile, web)"},
                {"name": "fc_restore_id", "description": "ID de restauração do FC"},
                {"name": "mgm_code", "description": "Codigo do MGM"},
                {"name": "mgm_valid_thru", "description": "MGM valido"},
                {"name": "cpf", "description": "CPF"},
                {"name": "phone_validated_at", "description": "Data da validação do telefone"},
                {"name": "bo_default_url", "description": "URL padrão do BO"},
                {"name": "cnpj", "description": "CNPJ"},
                {"name": "possible_email", "description": "Email possivel"},
                {"name": "partners_email_validated", "description": "Email de terceiro validado"},
                {"name": "identity_token_apple", "description": "Token apple"},
                {"name": "apple_authorization_code", "description": "Codigo de autorização da apple"},
                {"name": "apple_user", "description": "Usuário da apple"},
                {"name": "flg_not_receive_whatsapp", "description": "Foi notificado do recebimento de notificação Whatsapp"},
                {"name": "updated_at", "description": "Data de atualização"},
                {"name": "is_critical_customer", "description": "É cliente critico"},
                {"name": "bigquery_ingestion", "description": "Data da ultima carga"},
            ],
            5: 'WRITE_APPEND',
            6: ['postgres', 'append', 'user_account', 'clustered'],
            7: '@hourly',
            8: None,
            9: ['city_id','is_admin']
        }
        self.business = {
            1: "Negócio",
            2: "Salva dados de negócios",
            3:[
                {'name': 'id', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'description', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'user_id', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'created', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'},
                {'name': 'flg_validado', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'tax', 'type': 'NUMERIC', 'mode': 'NULLABLE'},
                {'name': 'signing_up', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'flg_pre_register', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'validated_at', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'},
                {'name': 'suspended', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'suspended_until', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'},
                {'name': 'source', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'company_enabled', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'customer_enabled', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'cnpj', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'status_slug', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'company_image_enabled', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'trade_name', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'company_display_name', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'charge_tax', 'type': 'NUMERIC', 'mode': 'NULLABLE'},
                {'name': 'short_description', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'work_since', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'bigquery_ingestion', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'}
            ],
            4:[
                {"name": "id", "description": "ID do estado"},
                {"name": "description", "description": "Nome do estado"},
                {"name": "user_id", "description": "ID do usuário"},
                {"name": "created", "description": "Data de Criação"},
                {"name": "flg_validado", "description": "Negócio validado"},
                {"name": "tax", "description": "Taxa"},
                {"name": "signing_up", "description": "Logado"},
                {"name": "flg_pre_register", "description": "Está em pré registro?"},
                {"name": "validated_at", "description": "Data de validação"},
                {"name": "suspended", "description": "Suspenço?"},
                {"name": "suspended_until", "description": "Suspenço até?"},
                {"name": "source", "description": "Origem (mobile, web)"},
                {"name": "company_enabled", "description": "Ativado para empresa?"},
                {"name": "customer_enabled", "description": "Ativado para cliente?"},
                {"name": "cnpj", "description": "CNPJ"},
                {"name": "status_slug", "description": "Status atual"},
                {"name": "company_image_enabled", "description": "Imagem da empresa ativa?"},
                {"name": "trade_name", "description": "Nome Comercial"},
                {"name": "company_display_name", "description": "Nome fantasia"},
                {"name": "charge_tax", "description": "Taxa cobrada"},
                {"name": "short_description", "description": "Descricão curta"},
                {"name": "work_since", "description": "Trabalha desde?"},
                {"name": "bigquery_ingestion", "description": "Data da ultima carga"},
            ],
            5: 'WRITE_APPEND',
            6: ['postgres', 'append', 'business', 'partitioned'],
            7: '0 0/6 * * *',
            8: {'type': 'DAY', 'field': 'created'},
            9: None
        }
        self.business_status = {
            1: "Status de Negócio",
            2: "Salva o status atual do negócio",
            3:[
                {'name': 'id', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'slug', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'text', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'active', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'bigquery_ingestion', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'}
            ],
            4:[
                {"name": "id", "description": "ID do estado"},
                {"name": "slug", "description": "Nome do estado"},
                {"name": "text", "description": "Sigla do estado"},
                {"name": "active", "description": "Data de criação"},
                {"name": "bigquery_ingestion", "description": "Data da ultima carga"},
            ],
            5: 'WRITE_TRUNCATE',
            6: ['postgres', 'truncate', 'business_status'],
            7: '0 0/6 * * *',
            8: None,
            9: None
        }
        self.state = {
            1: "Estados",
            2: "Tabela de cadastro de estados, populadas pelo usuário",
            3:[
                {'name': 'id', 'type': 'INTEGER', 'mode': 'NULLABLE'}, 
                {'name': 'name', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'initials', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'created', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'},
                {'name': 'enabled', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
                {'name': 'bigquery_ingestion', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'}
            ],
            4:[
                {"name": "id", "description": "ID do estado"},
                {"name": "name", "description": "Nome do estado"},
                {"name": "initials", "description": "Sigla do estado"},
                {"name": "created", "description": "Data de criação"},
                {"name": "enabled", "description": "Estado habilitado?"},
                {"name": "bigquery_ingestion", "description": "Data da ultima carga"},
            ],
            5: 'WRITE_TRUNCATE',
            6: ['postgres', 'truncate', 'state'],
            7: "@daily",
            8: None,
            9: None
        }
        self.business_task = {
            1: "Tarefas para profissionais",
            2: "Lista de tarefas vinculadas ao profissional, lista de distribuição, realizada pelo sistema a partir de uma tarefa aberta pelo cliente",
            3:[
                {"name": "id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "task_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "user_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "is_deleted", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "deleted_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "is_read", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "read_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "is_deal_read", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "deal_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "created", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "is_charged", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "charge_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "is_paid", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "paid_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "updated_at", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "business_task_deleted_reason", "type": "STRING", "mode": "NULLABLE"},
                {"name": "favorite", "type": "BOOLEAN", "mode": "NULLABLE"},
                {'name': 'bigquery_ingestion', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'}
            ],
            4:[
                {"name": "id", "description": "ID da tarefa de negócio"},
                {"name": "task_id", "description": "ID da tarefa"},
                {"name": "user_id", "description": "ID do usuário"},
                {"name": "is_deleted", "description": "Tarefa foi deletada?"},
                {"name": "deleted_date", "description": "Data de deleção da tarefa"},
                {"name": "is_read", "description": "Foi lido?"},
                {"name": "read_date", "description": "Data da leitura"},
                {"name": "is_deal_read", "description": "Foi lido pelo negociador?"},
                {"name": "deal_date", "description": "Data da leitura pelo negócio"},
                {"name": "created", "description": "Data de criação"},
                {"name": "is_charged", "description": "Foi cobrado?"},
                {"name": "charge_date", "description": "Data de cobrança"},
                {"name": "is_paid", "description": "Foi pago?"},
                {"name": "paid_date", "description": "Data do pagamento"},
                {"name": "updated_at", "description": "Data da atualização"},
                {"name": "business_task_deleted_reason", "description": "Razão pela deleção da tarefa"},
                {"name": "favorite", "description": "Descricao"},
                {"name": "bigquery_ingestion", "description": "Data da ultima carga"},
            ],
            5: 'WRITE_APPEND',
            6: ['postgres', 'append', 'business_task', 'partitioned'],
            7: '@hourly',
            8: {'type': 'DAY', 'field': 'created'},
            9: None
        }
        self.task_quote = {
            1: "Orçamentos",
            2: "Tabela responsável pelos orçamentos de cada tarefa aberta pelo B2C",
            3:[
                {"name": "id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "task_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "user_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "amount", "type": "NUMERIC", "mode": "NULLABLE"},
                {"name": "selected", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "is_new", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "created", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "selected_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "is_discarded", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "new_amount", "type": "NUMERIC", "mode": "NULLABLE"},
                {"name": "feedback_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "is_instant_match", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "new_amount_comment", "type": "STRING", "mode": "NULLABLE"},
                {"name": "tax", "type": "NUMERIC", "mode": "NULLABLE"},
                {"name": "approved", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "is_charged", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "charge_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "is_paid", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "paid_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "price", "type": "NUMERIC", "mode": "NULLABLE"},
                {"name": "price_old", "type": "NUMERIC", "mode": "NULLABLE"},
                {"name": "price_coupon", "type": "NUMERIC", "mode": "NULLABLE"},
                {"name": "price_credits", "type": "NUMERIC", "mode": "NULLABLE"},
                {"name": "transfer_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "task_description", "type": "STRING", "mode": "NULLABLE"},
                {"name": "task_price", "type": "NUMERIC", "mode": "NULLABLE"},
                {"name": "material_price", "type": "NUMERIC", "mode": "NULLABLE"},
                {"name": "price_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "updated_at", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "bigquery_ingestion", "type": "TIMESTAMP", "mode": "NULLABLE"}
            ],
            4:[
                {"name": "id", "description": "ID do orçamento"},
                {"name": "task_id", "description": "ID da tarefa"},
                {"name": "user_id", "description": "ID do usuário"},
                {"name": "amount", "description": "Quantia"},
                {"name": "selected", "description": "Selecionado"},
                {"name": "is_new", "description": "É novo?"},
                {"name": "created", "description": "Data de criação"},
                {"name": "selected_date", "description": "Data da seleção"},
                {"name": "is_discarded", "description": "Foi descartado?"},
                {"name": "new_amount", "description": "Nova Quantidade"},
                {"name": "feedback_id", "description": "ID do Feedback"},
                {"name": "is_instant_match", "description": "É calculado istantaneamente?"},
                {"name": "new_amount_comment", "description": "Novo comentario de quantidade"},
                {"name": "tax", "description": "Taxa"},
                {"name": "approved", "description": "Aprovado"},
                {"name": "is_charged", "description": "Foi Cobrado?"},
                {"name": "charge_date", "description": "Data da Cobrança"},
                {"name": "is_paid", "description": "Foi pago?"},
                {"name": "paid_date", "description": "Data de pagamento"},
                {"name": "price", "description": "Preço"},
                {"name": "price_old", "description": "preço antigo"},
                {"name": "price_coupon", "description": "Cupom"},
                {"name": "price_credits", "description": "Credito"},
                {"name": "transfer_date", "description": "Data de transferencia"},
                {"name": "task_description", "description": "Descrição da tarefa"},
                {"name": "task_price", "description": "Preço da tarefa"},
                {"name": "material_price", "description": "Preço do material"},
                {"name": "price_date", "description": "Data do preço"},
                {"name": "updated_at", "description": "Data da atualização"},
                {"name": "bigquery_ingestion", "description": "Data da ultima carga"},
            ],
            5: 'WRITE_APPEND',
            6: ['postgres', 'append', 'task_quote', 'partitioned'],
            7: "@hourly",
            8: {'type': 'DAY', 'field': 'created'},
            9: None
        }
        self.service = {
            1: "Serviços",
            2: "Tabela de cadastro de serviços",
            3:[
                {"name": "id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "text", "type": "STRING", "mode": "NULLABLE"},
                {"name": "img", "type": "STRING", "mode": "NULLABLE"},
                {"name": "position", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "created", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "css_class", "type": "STRING", "mode": "NULLABLE"},
                {"name": "default_description", "type": "STRING", "mode": "NULLABLE"},
                {"name": "photo", "type": "STRING", "mode": "NULLABLE"},
                {"name": "keywords", "type": "STRING", "mode": "NULLABLE"},
                {"name": "flg_step_by_step", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "version", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "allow_instant_match", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "web_icon", "type": "STRING", "mode": "NULLABLE"},
                {"name": "web_photo", "type": "STRING", "mode": "NULLABLE"},
                {"name": "icon", "type": "STRING", "mode": "NULLABLE"},
                {"name": "quote_step", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "service_group", "type": "STRING", "mode": "NULLABLE"},
                {"name": "parent_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "keywords_fast_format", "type": "STRING", "mode": "NULLABLE"},
                {"name": "description_orientation", "type": "STRING", "mode": "NULLABLE"},
                {"name": "is_stimulated_service", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "bigquery_ingestion", "type": "TIMESTAMP", "mode": "NULLABLE"}
            ],
            4:[
                {"name": "id", "description": "ID do serviço"},
                {"name": "text", "description": "Descricao do serviço"},
                {"name": "img", "description": "imagem"},
                {"name": "position", "description": "posição"},
                {"name": "created", "description": "Data de criação"},
                {"name": "css_class", "description": "Classe do CSS"},
                {"name": "default_description", "description": "Descricao padrão"},
                {"name": "photo", "description": "Foto"},
                {"name": "keywords", "description": "Palavra chave"},
                {"name": "flg_step_by_step", "description": "Passo a passo"},
                {"name": "version", "description": "Versão"},
                {"name": "allow_instant_match", "description": "Permite calculo instantaneo"},
                {"name": "web_icon", "description": "Icone web"},
                {"name": "web_photo", "description": "Foto Web"},
                {"name": "icon", "description": "Icone"},
                {"name": "quote_step", "description": "passo do orçamento"},
                {"name": "service_group", "description": "Grupo de serviço"},
                {"name": "parent_id", "description": "ID do Pai"},
                {"name": "keywords_fast_format", "description": "Palavra chave formato rápido"},
                {"name": "description_orientation", "description": "Descrição da orientação"},
                {"name": "is_stimulated_service", "description": "É serviço simulado?"},
                {"name": "bigquery_ingestion", "description": "Data da ultima carga"},
            ],
            5: 'WRITE_TRUNCATE',
            6: ['postgres', 'truncate', 'service'],
            7: "@daily",
            8: None,
            9: None
        }
        self.task_problem = {
            1: "Problema de tarefa",
            2: "Tabela de problemas relacionados as tarefas",
            3:[
                {"name": "id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "task_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "user_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "feedback_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "comments", "type": "STRING", "mode": "NULLABLE"},
                {"name": "created", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "updated_at", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "bigquery_ingestion", "type": "TIMESTAMP", "mode": "NULLABLE"}
            ],
            4:[
                {"name": "id", "description": "ID do problema"},
                {"name": "task_id", "description": "ID da tarefa"},
                {"name": "user_id", "description": "ID do usuário"},
                {"name": "feedback_id", "description": "ID do Feedback"},
                {"name": "comments", "description": "Comentário"},
                {"name": "created", "description": "Data de criação"},
                {"name": "updated_at", "description": "Data de atualização"},
                {"name": "bigquery_ingestion", "description": "Data da ultima carga"},
            ],
            5: 'WRITE_APPEND',
            6: ['postgres', 'append', 'task_problem', 'partitioned'],
            7: '0 0/6 * * *',
            8: {'type': 'DAY', 'field': 'created'},
            9: None
        }
        self.company = {
            1: "Empresa",
            2: "Tabela de cadastro de empresas B2B",
            3:[
                {"name": "id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "name", "type": "STRING", "mode": "NULLABLE"},
                {"name": "logo_url", "type": "STRING", "mode": "NULLABLE"},
                {"name": "is_active", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "created", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "square_logo_url", "type": "STRING", "mode": "NULLABLE"},
                {"name": "city_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "state_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "cnpj", "type": "STRING", "mode": "NULLABLE"},
                {"name": "accept_external_task", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "contract_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "styles", "type": "STRING", "mode": "NULLABLE"},
                {"name": "source", "type": "STRING", "mode": "NULLABLE"},
                {"name": "segment_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "responsibility_bucket_default", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "accept_payment_ticket", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "default_financial_email", "type": "STRING", "mode": "NULLABLE"},
                {"name": "address_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "billing_address_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "use_billing_company_info", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "task_agent_receives_email", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "commission_deal", "type": "NUMERIC", "mode": "NULLABLE"},
                {"name": "commission_deal_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "bigquery_ingestion", "type": "TIMESTAMP", "mode": "NULLABLE"}
            ],
            4:[
                {"name": "id", "description": "ID da empresa"},
                {"name": "name", "description": "Nome"},
                {"name": "logo_url", "description": "URL do logo"},
                {"name": "is_active", "description": "É ativa?"},
                {"name": "created", "description": "Data de Criação"},
                {"name": "square_logo_url", "description": "URL do logotipo quadrado"},
                {"name": "city_id", "description": "ID da Cidade"},
                {"name": "state_id", "description": "ID do Estado"},
                {"name": "cnpj", "description": "CNPJ"},
                {"name": "accept_external_task", "description": "Aceita tarefa externa?"},
                {"name": "contract_id", "description": "ID do contrato"},
                {"name": "styles", "description": "Estilos"},
                {"name": "source", "description": "Origem"},
                {"name": "segment_id", "description": "ID do segmento"},
                {"name": "responsibility_bucket_default", "description": "Repositorio padrão de responsabilidade"},
                {"name": "accept_payment_ticket", "description": "Aceita ticket de pagamento?"},
                {"name": "default_financial_email", "description": "Email padrão para financeiro"},
                {"name": "address_id", "description": "ID do endereço"},
                {"name": "billing_address_id", "description": "ID do endereço de cobrança"},
                {"name": "use_billing_company_info", "description": "Usar informacão de cobrança da Empresa"},
                {"name": "task_agent_receives_email", "description": "Agente da tarefa recebe email?"},
                {"name": "commission_deal", "description": "Comissão para negociante"},
                {"name": "commission_deal_date", "description": "Data da comissão"},
                {"name": "bigquery_ingestion", "description": "Data da ultima carga"},
            ],
            5: 'WRITE_TRUNCATE',
            6: ['postgres', 'truncate', 'company'],
            7: "@daily",
            8: None,
            9: None
        }
        self.contact = {
            1: "Contato",
            2: "Tabela que grava status do contato (falha, sucesso...)",
            3:[
                {"name": "id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "slug", "type": "STRING", "mode": "NULLABLE"},
                {"name": "text", "type": "STRING", "mode": "NULLABLE"},
                {"name": "has_comment", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "created", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "bigquery_ingestion", "type": "TIMESTAMP", "mode": "NULLABLE"}
            ],
            4:[
                {"name": "id", "description": "ID do contato"},
                {"name": "slug", "description": "Status"},
                {"name": "text", "description": "Descricão do Status"},
                {"name": "has_comment", "description": "Tem comentário?"},
                {"name": "created", "description": "Data da Criação"},
                {"name": "bigquery_ingestion", "description": "Data da ultima carga"},
            ],
            5: 'WRITE_TRUNCATE',
            6: ['postgres', 'truncate', 'contact'],
            7: "@weekly",
            8: None,
            9: None
        }
        self.task = {
            1: "Tarefas",
            2: "Tabela de tarefas, onde o usuário pode solicitar a prestacão de determinado serviço, evidenciando contato e endereco e demais informações para que um profissional possa realizar alguma cotação",
            3:[
                {"name": "id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "description", "type": "STRING", "mode": "NULLABLE"},
                {"name": "address", "type": "STRING", "mode": "NULLABLE"},
                {"name": "phone", "type": "STRING", "mode": "NULLABLE"},
                {"name": "specific_date", "type": "timestamp without time zone", "mode": "NULLABLE"},
                {"name": "quotes", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "new_quotes", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "user_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "service_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "city_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "type_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "time_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "period_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "created", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "archived", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "closed", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "address_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "max_quotes", "type": "smallint", "mode": "NULLABLE"},
                {"name": "last_quote_request", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "payment_gateway", "type": "STRING", "mode": "NULLABLE"},
                {"name": "customer_card_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "source", "type": "STRING", "mode": "NULLABLE"},
                {"name": "specific_business_user_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "specific_business_user_only", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "coupon_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "installments", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "ab_test", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "expiration_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "auto_payment", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "from_tenant", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "company_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "schedule_confirmed", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "schedule_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "status", "type": "STRING", "mode": "NULLABLE"},
                {"name": "user_credits", "type": "NUMERIC", "mode": "NULLABLE"},
                {"name": "algorithm_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "responsibility_bucket_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "training", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "archived_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "is_needed_visit", "type": "BOOLEAN", "mode": "NULLABLE"},
                {"name": "operator_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "checkout_token", "type": "STRING", "mode": "NULLABLE"},
                {"name": "checkout_token_created_at", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "payment_user_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "checkout_finished_at", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "integration_task_id", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "updated_at", "type": "TIMESTAMP", "mode": "NULLABLE"},
                {"name": "score_fast_format", "type": "INTEGER", "mode": "NULLABLE"},
                {"name": "bigquery_ingestion", "type": "TIMESTAMP", "mode": "NULLABLE"}
            ],
            4:[
                {"name": "id", "description": "Descricao"},
                {"name": "description", "description": "Descricao"},
                {"name": "address", "description": "Descricao"},
                {"name": "phone", "description": "Descricao"},
                {"name": "specific_date", "description": "Descricao"},
                {"name": "quotes", "description": "Descricao"},
                {"name": "new_quotes", "description": "Descricao"},
                {"name": "user_id", "description": "Descricao"},
                {"name": "service_id", "description": "Descricao"},
                {"name": "city_id", "description": "Descricao"},
                {"name": "type_id", "description": "Descricao"},
                {"name": "time_id", "description": "Descricao"},
                {"name": "period_id", "description": "Descricao"},
                {"name": "created", "description": "Descricao"},
                {"name": "archived", "description": "Descricao"},
                {"name": "closed", "description": "Descricao"},
                {"name": "address_id", "description": "Descricao"},
                {"name": "max_quotes", "description": "Descricao"},
                {"name": "last_quote_request", "description": "Descricao"},
                {"name": "payment_gateway", "description": "Descricao"},
                {"name": "customer_card_id", "description": "Descricao"},
                {"name": "source", "description": "Descricao"},
                {"name": "specific_business_user_id", "description": "Descricao"},
                {"name": "specific_business_user_only", "description": "Descricao"},
                {"name": "coupon_id", "description": "Descricao"},
                {"name": "installments", "description": "Descricao"},
                {"name": "ab_test", "description": "Descricao"},
                {"name": "expiration_date", "description": "Descricao"},
                {"name": "auto_payment", "description": "Descricao"},
                {"name": "from_tenant", "description": "Descricao"},
                {"name": "company_id", "description": "Descricao"},
                {"name": "schedule_confirmed", "description": "Descricao"},
                {"name": "schedule_date", "description": "Descricao"},
                {"name": "status", "description": "Descricao"},
                {"name": "user_credits", "description": "Descricao"},
                {"name": "algorithm_id", "description": "Descricao"},
                {"name": "responsibility_bucket_id", "description": "Descricao"},
                {"name": "training", "description": "Descricao"},
                {"name": "archived_date", "description": "Descricao"},
                {"name": "is_needed_visit", "description": "Descricao"},
                {"name": "operator_id", "description": "Descricao"},
                {"name": "checkout_token", "description": "Descricao"},
                {"name": "checkout_token_created_at", "description": "Descricao"},
                {"name": "payment_user_id", "description": "Descricao"},
                {"name": "checkout_finished_at", "description": "Descricao"},
                {"name": "integration_task_id", "description": "Descricao"},
                {"name": "updated_at", "description": "Descricao"},
                {"name": "score_fast_format", "description": "Descricao"},
                {"name": "bigquery_ingestion", "description": "Data da ultima carga"},
            ],
            5: 'WRITE_APPEND',
            6: ['postgres', 'append', 'task', 'partitioned'],
            7: "@hourly",
            8: {'type': 'DAY', 'field': 'created'},
            9: None
        }